import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.filechooser.FileSystemView;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author GORAS
 */
public class Accueil extends javax.swing.JFrame {

    /**
     * Creates new form Accueil
     */
    public Accueil() {
        initComponents();
        this.setTitle("Graphio");
        this.setSize(1000, 600);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPalette = new javax.swing.JPanel();
        panelPropriétés = new javax.swing.JPanel();
        zoneDessin = new javax.swing.JScrollPane();
        menuBarre = new javax.swing.JMenuBar();
        menuGraphe = new javax.swing.JMenu();
        nouveauGraphe = new javax.swing.JMenuItem();
        enregistrer = new javax.swing.JMenuItem();
        enregistrerSous = new javax.swing.JMenuItem();
        ouvrir = new javax.swing.JMenuItem();
        menuEdition = new javax.swing.JMenu();
        undo = new javax.swing.JMenuItem();
        redo = new javax.swing.JMenuItem();
        menuTraitements = new javax.swing.JMenu();
        menuAide = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(null);

        panelPalette.setBackground(new java.awt.Color(204, 204, 204));
        panelPalette.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelPalette.setForeground(new java.awt.Color(204, 204, 204));
        panelPalette.setLayout(null);
        getContentPane().add(panelPalette);
        panelPalette.setBounds(0, 0, 210, 250);

        panelPropriétés.setBackground(new java.awt.Color(204, 204, 204));
        panelPropriétés.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout panelPropriétésLayout = new javax.swing.GroupLayout(panelPropriétés);
        panelPropriétés.setLayout(panelPropriétésLayout);
        panelPropriétésLayout.setHorizontalGroup(
            panelPropriétésLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 208, Short.MAX_VALUE)
        );
        panelPropriétésLayout.setVerticalGroup(
            panelPropriétésLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 248, Short.MAX_VALUE)
        );

        getContentPane().add(panelPropriétés);
        panelPropriétés.setBounds(0, 250, 210, 250);

        zoneDessin.setBackground(new java.awt.Color(255, 255, 255));
        zoneDessin.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        zoneDessin.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        getContentPane().add(zoneDessin);
        zoneDessin.setBounds(210, 0, 680, 500);

        menuGraphe.setText("Graphes");

        nouveauGraphe.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        nouveauGraphe.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gouzy\\Documents\\BUT Info\\Semestre 3\\SAE\\Graphe\\GORAS_EditeurGrapheProbalistiques\\src\\main\\java\\img\\line-chart.png")); // NOI18N
        nouveauGraphe.setText("Nouveau graphe");
        nouveauGraphe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nouveauGrapheActionPerformed(evt);
            }
        });
        menuGraphe.add(nouveauGraphe);

        enregistrer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        enregistrer.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gouzy\\Documents\\BUT Info\\Semestre 3\\SAE\\Graphe\\GORAS_EditeurGrapheProbalistiques\\src\\main\\java\\img\\disquette.png")); // NOI18N
        enregistrer.setText("Enregistrer");
        enregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enregistrerActionPerformed(evt);
            }
        });
        menuGraphe.add(enregistrer);

        enregistrerSous.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        enregistrerSous.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gouzy\\Documents\\BUT Info\\Semestre 3\\SAE\\Graphe\\GORAS_EditeurGrapheProbalistiques\\src\\main\\java\\img\\disquette.png")); // NOI18N
        enregistrerSous.setText("Enregistrer sous");
        enregistrerSous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enregistrerSousActionPerformed(evt);
            }
        });
        menuGraphe.add(enregistrerSous);

        ouvrir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        ouvrir.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gouzy\\Documents\\BUT Info\\Semestre 3\\SAE\\Graphe\\GORAS_EditeurGrapheProbalistiques\\src\\main\\java\\img\\folder.png")); // NOI18N
        ouvrir.setText("Ouvrir");
        ouvrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ouvrirActionPerformed(evt);
            }
        });
        menuGraphe.add(ouvrir);

        menuBarre.add(menuGraphe);

        menuEdition.setText("Edition");

        undo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        undo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gouzy\\Documents\\BUT Info\\Semestre 3\\SAE\\Graphe\\GORAS_EditeurGrapheProbalistiques\\src\\main\\java\\img\\undo.png")); // NOI18N
        undo.setText("UnDo");
        undo.setToolTipText("");
        undo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                undoActionPerformed(evt);
            }
        });
        menuEdition.add(undo);

        redo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Y, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        redo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gouzy\\Documents\\BUT Info\\Semestre 3\\SAE\\Graphe\\GORAS_EditeurGrapheProbalistiques\\src\\main\\java\\img\\redo.png")); // NOI18N
        redo.setText("ReDo");
        redo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redoActionPerformed(evt);
            }
        });
        menuEdition.add(redo);

        menuBarre.add(menuEdition);

        menuTraitements.setText("Traitements");
        menuBarre.add(menuTraitements);

        menuAide.setText("Aide");
        menuBarre.add(menuAide);

        setJMenuBar(menuBarre);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void undoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_undoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_undoActionPerformed

    private void redoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_redoActionPerformed

    private void nouveauGrapheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nouveauGrapheActionPerformed
        new NouveauGraphe().setVisible(true);
    }//GEN-LAST:event_nouveauGrapheActionPerformed

    private void enregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enregistrerActionPerformed
        //TODO
    }//GEN-LAST:event_enregistrerActionPerformed

    private void enregistrerSousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enregistrerSousActionPerformed
        JFileChooser explorateurFichier = new JFileChooser(
                FileSystemView.getFileSystemView().getHomeDirectory());
        explorateurFichier.setDialogTitle("Enregistrer");
        
        int res = explorateurFichier.showSaveDialog(null);
        if(res == JFileChooser.APPROVE_OPTION) {
            File file = explorateurFichier.getSelectedFile();
            System.out.println(file.getAbsolutePath());
        }
        
    }//GEN-LAST:event_enregistrerSousActionPerformed

    private void ouvrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ouvrirActionPerformed
        JFileChooser explorateurFichier = new JFileChooser(
                FileSystemView.getFileSystemView().getHomeDirectory());
        explorateurFichier.setDialogTitle("Ouvrir un graphe: ");
        
        /* Gestion des extensions */
        explorateurFichier.setAcceptAllFileFilterUsed(false);
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Graphe ext1 et ext2", "A COMPLETER"); //TODO Extension OK
        explorateurFichier.addChoosableFileFilter(filter);
        
        int res = explorateurFichier.showOpenDialog(null);
        if(res == JFileChooser.APPROVE_OPTION) {
            File file = explorateurFichier.getSelectedFile();
            System.out.println(file.getAbsolutePath());
        }
    }//GEN-LAST:event_ouvrirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Accueil().setVisible(true);            
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem enregistrer;
    private javax.swing.JMenuItem enregistrerSous;
    private javax.swing.JMenu menuAide;
    private javax.swing.JMenuBar menuBarre;
    private javax.swing.JMenu menuEdition;
    private javax.swing.JMenu menuGraphe;
    private javax.swing.JMenu menuTraitements;
    private javax.swing.JMenuItem nouveauGraphe;
    private javax.swing.JMenuItem ouvrir;
    private javax.swing.JPanel panelPalette;
    private javax.swing.JPanel panelPropriétés;
    private javax.swing.JMenuItem redo;
    private javax.swing.JMenuItem undo;
    private javax.swing.JScrollPane zoneDessin;
    // End of variables declaration//GEN-END:variables
}
